### ISSUE TITLE
CBC mode

### ISSUE THREAD

**Issue by spaniakos** [Octoate/ArduinoDES#4]
hello octoate.

i am converting your library to a more sofisticated stacture, implementing the IV and KEY in the class and coding some improvements. I will do that for the reaspberry as well.

The main limitation of the advanced library so far is, trying to encrypt more than 160 bytes of input data (not including the padding) the programm crush. Probably from memory fragmentation as there are many memory blocks needed in order to declare, pad and encrypt the given plaintext string (byte [] = "test..........."). do you think 160 bytes of input data as suficient for the arduino? if yes, i will finish the library (only the padding validation check while decrypting is left to inmplement), and i will make the code compatible with raspberry Pi as well. Moreover i will make a new pull request for you to see the changes and if you want commit them in your respository as well.

Thanks spaniakos

**Comment by Octoate** [comment]
Hi spaniakos,
sorry for my late answer. Unfortunately I hadn't much time during the last months to work on any private projects :-(. Well, I guess, that 160bytes might be enough, but the idea was to have a library which is also able to stream data through it. E.g. with using an input buffer with one input block and an output buffer, which contains the output block after encryption. So you can fill the input buffer, encrypt it and send the output buffer while again filling the input buffer again.
An user can then decide whether he needs a fixed message size or not. I will have a look at your changes as soon as possible and test them on an Arduino Leonardo and then integrate your pull-request. 

Thanks a lot for your work!
Tim

**Comment by spaniakos** [comment]
Hello.

All those problems are solved.
I think the library is 100% working.
The only controversial is the padding process.
But this is easily changeable.
